import React,{useState} from 'react';
import { View, Text, ScrollView, TouchableOpacity, StyleSheet, Alert } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { BlurView } from 'expo-blur';
import { router } from 'expo-router';
const S=[{t:'Identity & Eligibility',c:'I am 18+, legally permitted to work in Kenya, and all information I provided is accurate.'},{t:'Certificate of Good Conduct',c:'I will provide a valid DCI Kenya Certificate of Good Conduct (KSh 1,050). My account goes live only after verification.'},{t:'Child Safety Commitment',c:'I commit to the safety, wellbeing and dignity of every child. I will never harm any child physically, emotionally, or sexually.'},{t:'Professional Conduct',c:'I will be punctual, reliable, and communicate professionally. No unauthorized persons at bookings.'},{t:'Confidentiality',c:'I will keep all family information confidential. No photos of children on social media without written parental consent.'},{t:'Platform Fee',c:'I accept the KSh 50 platform fee per booking deducted from my earnings.'},{t:'Termination',c:'Safe Totos may terminate my account for child safety violations, fraud, false documents, or repeated misconduct.'}];
export default function CaregiverAgreement(){
const [agreed,setAgreed]=useState(false);
return(<View style={s.root}><View style={s.ov}/><SafeAreaView style={s.safe}><View style={s.hdr}><TouchableOpacity onPress={()=>router.back()} style={s.back}><Text style={s.backT}>←</Text></TouchableOpacity><Text style={s.hdrT}>Caregiver Agreement</Text><View style={{width:36}}/></View><ScrollView contentContainerStyle={s.content}><BlurView intensity={20} tint="dark" style={s.intro}><Text style={s.introE}>🤝</Text><Text style={s.introT}>Please read each clause carefully before agreeing.</Text></BlurView>{S.map((x,i)=>(<BlurView key={i} intensity={18} tint="dark" style={s.card}><View style={s.ch}><View style={s.cn}><Text style={s.cnT}>{i+1}</Text></View><Text style={s.ct}>{x.t}</Text></View><Text style={s.cc}>{x.c}</Text></BlurView>))}<TouchableOpacity style={[s.btn,agreed&&s.btnOn]} onPress={()=>{setAgreed(true);Alert.alert('Agreement Accepted','Thank you for committing to Safe Totos standards.');}} activeOpacity={0.85}><Text style={s.btnT}>{agreed?'✓ Agreement Accepted':'I Agree to All Terms'}</Text></TouchableOpacity><View style={{height:40}}/></ScrollView></SafeAreaView></View>);}
const s=StyleSheet.create({root:{flex:1,backgroundColor:'#080C14'},ov:{position:'absolute',width:'100%',height:'100%',backgroundColor:'rgba(8,12,20,0.96)'},safe:{flex:1},hdr:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',paddingHorizontal:16,paddingVertical:14,borderBottomWidth:1,borderBottomColor:'rgba(255,255,255,0.06)'},back:{width:36,height:36,borderRadius:10,backgroundColor:'rgba(255,255,255,0.06)',alignItems:'center',justifyContent:'center'},backT:{color:'#BAE6FD',fontSize:18},hdrT:{color:'#F0F9FF',fontWeight:'800',fontSize:16},content:{paddingHorizontal:16,paddingTop:16},intro:{borderRadius:16,overflow:'hidden',padding:16,marginBottom:16,borderWidth:1,borderColor:'rgba(56,189,248,0.15)',flexDirection:'row',alignItems:'center',gap:12},introE:{fontSize:28},introT:{flex:1,color:'rgba(186,230,253,0.7)',fontSize:13,lineHeight:20},card:{borderRadius:16,overflow:'hidden',padding:16,marginBottom:10,borderWidth:1,borderColor:'rgba(255,255,255,0.07)'},ch:{flexDirection:'row',alignItems:'center',gap:10,marginBottom:8},cn:{width:24,height:24,borderRadius:8,backgroundColor:'rgba(56,189,248,0.15)',alignItems:'center',justifyContent:'center'},cnT:{color:'#38BDF8',fontSize:11,fontWeight:'800'},ct:{color:'#F0F9FF',fontWeight:'800',fontSize:14,flex:1},cc:{color:'rgba(186,230,253,0.7)',fontSize:13,lineHeight:21},btn:{backgroundColor:'#0284C7',borderRadius:16,paddingVertical:16,alignItems:'center',marginTop:8},btnOn:{backgroundColor:'#34D399'},btnT:{color:'#fff',fontWeight:'800',fontSize:15}});
